[package]
name = "rust-game-of-life"
version = "0.1.0"
authors = ["RÃ©mi Bardon <remi.bardon.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
